---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: manifests
  namespace: flux-system
spec:
  path: "./manifests"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  interval: 1m
