---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  targetNamespace: cert-manager
  install:
    createNamespace: true
  interval: 1m
  dependsOn:
    - name: promstack
      namespace: flux-system
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        namespace: monitoring
        interval: 30s
        scrapeTimeout: 10s
