---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  interval: 1m
  url: https://haproxy-ingress.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  releaseName: haproxy-ingress
  chart:
    spec:
      chart: haproxy-ingress
      version: 54.2.2
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
  targetNamespace: gateway
  dependsOn:
    - name: promstack
      namespace: flux-system
  install:
    createNamespace: true
  interval: 1m
  values:
    controller:
      ingressClass: haproxy
      stats:
        enabled: true
      metrics:
        enabled: true
      servicemonitor:
        enabled: true
