---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promstack
  namespace: flux-system
spec:
  releaseName: promstack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 54.2.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  targetNamespace: monitoring
  install:
    createNamespace: true
  interval: 1m
  values:
    alertmanager:
      enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
---
