---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stackgres-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stackgres-operator
  namespace: flux-system
spec:
  releaseName: stackgres-operator
  chart:
    spec:
      chart: stackgres-operator
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: stackgres
        namespace: flux-system
  targetNamespace: stackgres
  install:
    createNamespace: true
  interval: 1m
  dependsOn:
    - name: promstack
      namespace: flux-system
  values:
    grafana:
      autoEmbed: true
      webHost: promstack-grafana.monitoring.svc.cluster.local
      secretNamespace: monitoring
      secretName: prometheus-grafana
