---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  targetNamespace: cert-manager
  install:
    createNamespace: true
    retries: 10
  interval: 1m
  dependsOn:
    - name: promstack
      namespace: flux-system
  values:
    - --set installCRDs=true
    - --set prometheus.enabled=true
    - --set prometheus.servicemonitor.enabled=true
    - --set prometheus.servicemonitor.namespace=monitoring
    - --set prometheus.servicemonitor.interval=30s
    - --set prometheus.servicemonitor.scrapeTimeout=10s
