apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promstack
  namespace: flux-system
spec:
  releaseName: promstack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 54.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  targetNamespace: monitoring
  install:
    createNamespace: true
  values:
    alertmanager:
      enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
