apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promstack
  namespace: flux-system
spec:
  releaseName: promstack
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-stack
    version: 14.5.0
  targetNamespace: monitoring
  values:
    alertmanager:
      enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
