---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: manifests-common
  namespace: flux-system
spec:
  path: "./manifests/base"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  interval: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: manifests-cluster
  namespace: flux-system
spec:
  path: "./manifests/homesvc"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  interval: 1m
